data:
    type: "LLdataset"
    train_dataset: ""
    val_dataset: ""
    patch_size: 256
    channels: 3
    num_workers: 4
    data_dir: "/media/NAS/DATASET/LOLI_ACCV"
    ckpt_dir: "ckpt/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

uvit:  # Configuration for the U-ViT model
    ch: 64  # Channel dimension for embeddings
    num_heads: 8  # Number of attention heads
    mlp_ratio: 4.0  # Ratio of MLP hidden dimension to embedding dimension
    depth: 6  # Number of transformer blocks

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200

training:
    batch_size: 8
    n_epochs: 500
    validation_freq: 1000

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8
